# Generated by Django 3.2 on 2021-05-31 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0005_rama_stock_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeTimber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('quantity', models.IntegerField()),
                ('volume', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Timber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('wood_species', models.CharField(choices=[('pine', 'Сосна'), ('larch', 'Лиственница')], max_length=20)),
                ('diameter', models.IntegerField()),
                ('length', models.IntegerField()),
                ('volume', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('volume', models.FloatField()),
                ('income_timber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='rawstock.incometimber')),
                ('rama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timber_records', to='stock.rama')),
                ('timber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='rawstock.timber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
