# Generated by Django 3.2 on 2021-05-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstock', '0006_incometimber_rama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incometimber',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
