# Generated by Django 3.2 on 2021-05-31 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rawstock', '0007_alter_incometimber_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incometimber',
            name='date',
        ),
    ]
