# Generated by Django 3.2 on 2021-05-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rawstock', '0008_remove_incometimber_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='incometimber',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
