# Generated by Django 3.2 on 2021-05-31 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_rama_stock_type'),
        ('rawstock', '0009_incometimber_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('volume_quota_brus', models.FloatField()),
                ('volume_quota_doska', models.FloatField()),
                ('income_timber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rawstock.incometimber')),
                ('rama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotas', to='stock.rama')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
