# Generated by Django 3.2 on 2021-05-31 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rawstock', '0010_quota'),
    ]

    operations = [
        migrations.AddField(
            model_name='quota',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotas', to=settings.AUTH_USER_MODEL),
        ),
    ]
