# Generated by Django 3.2 on 2021-06-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rawstock', '0011_quota_initiator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timberrecord',
            name='income_timber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timber_records', to='rawstock.incometimber'),
        ),
    ]
