# Generated by Django 3.2 on 2021-05-24 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cashrecord',
            name='rama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_records', to='stock.rama'),
        ),
        migrations.AlterField(
            model_name='cashrecord',
            name='record_type',
            field=models.CharField(choices=[('payout_to_employee_from_shift', 'Начисление работникам'), ('withdraw_employee', 'Обналичивание работникам'), ('withdraw_cash_from_manager', 'Вывод средств от кладмэна/менеджера'), ('rama_expenses', 'Расходы рамы'), ('sale_income', 'Приход с продажи')], max_length=50),
        ),
    ]
