# Generated by Django 3.2 on 2021-05-19 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('width', models.FloatField()),
                ('length', models.FloatField()),
                ('height', models.FloatField()),
                ('volume', models.FloatField()),
                ('employee_rate', models.IntegerField(default=0)),
                ('market_cost', models.IntegerField(default=0)),
                ('china_width', models.FloatField(blank=True, null=True)),
                ('china_length', models.FloatField(blank=True, null=True)),
                ('china_height', models.FloatField(blank=True, null=True)),
                ('china_volume', models.FloatField(blank=True, null=True)),
                ('round_volume', models.FloatField(default=0)),
                ('wood_species', models.CharField(choices=[('pine', 'Сосна'), ('larch', 'Лиственница')], max_length=20)),
                ('lumber_type', models.CharField(choices=[('brus', 'brus'), ('doska', 'doska')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('shift_type', models.CharField(choices=[('day', 'День'), ('night', 'Ночь')], max_length=10)),
                ('volume', models.FloatField(null=True)),
                ('employee_cash', models.FloatField(null=True)),
                ('cash_per_employee', models.FloatField(null=True)),
                ('back_calc_volume', models.FloatField(null=True)),
                ('back_calc_cash', models.FloatField(null=True)),
                ('back_calc_cash_per_employee', models.FloatField(null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('employees', models.ManyToManyField(to='accounts.Account')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('rama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='stock.rama')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sale_type', models.CharField(blank=True, choices=[('person', 'Физ. лицо'), ('perekup', 'Перекуп'), ('china', 'Китай')], max_length=20, null=True)),
                ('client', models.CharField(blank=True, max_length=20, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('rama_total_cash', models.IntegerField(default=0)),
                ('selling_total_cash', models.IntegerField(default=0)),
                ('seller_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('kladman_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('loader_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('delivery_fee', models.IntegerField(blank=True, default=0, null=True)),
                ('add_expenses', models.IntegerField(blank=True, default=0, null=True)),
                ('bonus_kladman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_bonus_kladman', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('rama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='stock.rama')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LumberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField(default=0)),
                ('volume', models.FloatField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('total_cash', models.FloatField(default=0)),
                ('back_total_cash', models.FloatField(default=0)),
                ('rama_price', models.IntegerField(default=0)),
                ('rama_total_cash', models.FloatField(default=0)),
                ('selling_price', models.IntegerField(default=0)),
                ('selling_total_cash', models.FloatField(default=0)),
                ('selling_calc_type', models.CharField(blank=True, max_length=10, null=True)),
                ('lumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='stock.lumber')),
                ('rama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lumber_records', to='stock.rama')),
                ('sale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lumber_records', to='stock.sale')),
                ('shift', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lumber_records', to='stock.shift')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
