# Generated by Django 3.2 on 2021-05-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lumber',
            options={'ordering': ['lumber_type', 'wood_species']},
        ),
    ]
