# Generated by Django 3.2 on 2021-05-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('stock', '0002_alter_lumber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumberrecord',
            name='record_type',
            field=models.CharField(blank=True, choices=[('shift_record', 'shift_record'), ('sale_record', 'sale_record'), ('resaw_record', 'resaw_record')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ReSaw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('employee_cash', models.IntegerField(default=0)),
                ('employees', models.ManyToManyField(to='accounts.Account')),
                ('lumber_in', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_saw_in', to='stock.lumberrecord')),
                ('lumber_out', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='re_saw_out', to='stock.lumberrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
