# Generated by Django 3.2 on 2021-05-26 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_auto_20210525_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='resaw',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resaws', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lumberrecord',
            name='record_type',
            field=models.CharField(blank=True, choices=[('shift_record', 'shift_record'), ('sale_record', 'sale_record'), ('resaw_record', 'resaw_record'), ('refuse_record', 'refuse_record')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lumberrecord',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lumber_records', to='stock.sale'),
        ),
        migrations.AlterField(
            model_name='lumberrecord',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lumber_records', to='stock.shift'),
        ),
        migrations.AlterField(
            model_name='resaw',
            name='employee_cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resaw',
            name='lumber_in',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='re_saw_in', to='stock.lumberrecord'),
        ),
        migrations.AlterField(
            model_name='resaw',
            name='lumber_out',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='re_saw_out', to='stock.lumberrecord'),
        ),
        migrations.CreateModel(
            name='RefuseLumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refuses', to=settings.AUTH_USER_MODEL)),
                ('lumber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refuse', to='stock.lumberrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
