# Generated by Django 3.2 on 2021-05-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20210526_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='rama',
            name='stock_type',
            field=models.CharField(blank=True, choices=[('mixed', 'Смешанный'), ('sorted', 'Сортированный')], max_length=50, null=True),
        ),
    ]
