# Generated by Django 3.2 on 2021-06-02 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_shift_quota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='quota',
        ),
    ]
