# Generated by Django 3.2 on 2021-07-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210706_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='resaw',
            name='rama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resaws', to='stock.rama'),
        ),
    ]
