# Generated by Django 3.2 on 2021-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('nickname', models.CharField(blank=True, max_length=20, null=True)),
                ('is_ramshik', models.BooleanField(default=False)),
                ('is_senior_ramshik', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_kladman', models.BooleanField(default=False)),
                ('is_seller', models.BooleanField(default=False)),
                ('cash', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
