# Generated by Django 3.2 on 2021-05-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
    ]
