# Generated by Django 3.2 on 2021-07-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210706_1522'),
        ('accounts', '0004_account_can_see_rama_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_see_rama_shift',
            field=models.ManyToManyField(related_name='accounts_can_see_shift', to='stock.Rama'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_capo',
            field=models.BooleanField(default=False),
        ),
    ]
