# Generated by Django 3.2 on 2021-07-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210706_1522'),
        ('accounts', '0005_auto_20210707_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_see_rama_sales',
            field=models.ManyToManyField(related_name='accounts_can_see_sales', to='stock.Rama'),
        ),
    ]
