# Generated by Django 3.2 on 2021-07-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210706_1522'),
        ('accounts', '0006_account_can_see_rama_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_see_rama_cash',
            field=models.ManyToManyField(related_name='accounts_can_see_cash', to='stock.Rama'),
        ),
    ]
