# Generated by Django 3.2 on 2021-07-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_auto_20210706_1522'),
        ('accounts', '0007_account_can_see_rama_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_see_rama_daily_cash_report',
            field=models.ManyToManyField(blank=True, related_name='accounts_can_see_rama_daily_cash_report', to='stock.Rama'),
        ),
        migrations.AlterField(
            model_name='account',
            name='can_see_rama_cash',
            field=models.ManyToManyField(blank=True, related_name='accounts_can_see_cash', to='stock.Rama'),
        ),
        migrations.AlterField(
            model_name='account',
            name='can_see_rama_sales',
            field=models.ManyToManyField(blank=True, related_name='accounts_can_see_sales', to='stock.Rama'),
        ),
        migrations.AlterField(
            model_name='account',
            name='can_see_rama_shift',
            field=models.ManyToManyField(blank=True, related_name='accounts_can_see_shift', to='stock.Rama'),
        ),
        migrations.AlterField(
            model_name='account',
            name='can_see_rama_stock',
            field=models.ManyToManyField(blank=True, related_name='accounts_can_see_stock', to='stock.Rama'),
        ),
    ]
