# Generated by Django 3.2 on 2021-07-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_resaw_rama'),
        ('accounts', '0008_auto_20210713_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='can_see_rama_resaws',
            field=models.ManyToManyField(blank=True, related_name='accounts_can_see_resaws', to='stock.Rama'),
        ),
    ]
